#!/bin/bash
#
# @author Disparity <disparity-github@yandex.ru>
# @site https://github.com/Disparity/git-hooks
# @dependency git
# @dependency php@>=5.3
# @dependency composer@~1.0

if [ "$1" == "$2" ]; then exit 0; fi

rm -rf `git rev-parse --show-toplevel`/var/cache/dev
php `git rev-parse --show-toplevel`/bin/console cache:clear -q --no-warmup
php `git rev-parse --show-toplevel`/bin/console cache:clear -q --no-warmup --env=test --no-interaction

exit 0
