#!/bin/bash
#
# Rolls back the absence of migration and migrate
#
# @author Disparity <disparity-github@yandex.ru>
# @site https://github.com/Disparity/git-hooks
# @dependency git
# @dependency php@>=5.3
# @dependency doctrine/doctrine-migrations-bundle@~1.1

if [ "$1" == "$2" ]; then exit 0; fi
app_console="`git rev-parse --show-toplevel`/app/console --no-ansi -n"
if [ ! -d "`$app_console debug:container --parameter=doctrine_migrations.dir_name`" ]; then exit 0; fi

cd `$app_console debug:container --parameter=doctrine_migrations.dir_name` && cd - > /dev/null #fix mingw + php realpath + git issue

for i in $(git diff --name-only --diff-filter=AM $2 $1 -- ${OLDPWD}|sort -r); do
    git checkout $1 -- ${i} > /dev/null && git reset ${i} > /dev/null
    migration=`echo ${i} | sed -e 's/.*[^0-9]\([0-9]*\)\.php$/\1/'`

    ( $app_console doctrine:migration:status --show-versions | grep $migration | grep -Eq '^.*[0-9]\) *migrated *$' > /dev/null ) && (
        $app_console doctrine:migration:execute --quiet --down $migration &&
        echo Reverted version $migration || echo Reverted version $migration failed
    )
    if [ "`git diff --name-only --diff-filter=M $2 $1 -- ${i}`" ]; then
        git checkout -- "${i}"
    else
        rm "${i}"
    fi
done

($app_console doctrine:migration:status --show-versions|grep 'not migrated' > /dev/null) && (
    $app_console doctrine:migration:migrate -vvv|grep '(version)'|sed -e 's/.*\[\"\([0-9]*\)\"\]/Migrated version \1/' || echo Migration failed
)
exit 0
