#!/bin/bash
#
# @author Disparity <disparity-github@yandex.ru>
# @site https://github.com/Disparity/git-hooks
# @dependency git

for i in $(find `git rev-parse --git-dir`/hooks -type f -perm /111 -name `basename $0`-* -print|sort); do
    ${i} $1 $2 $3 || exit -1
done
