#!/bin/bash
#
# PHP syntax check via php -l
#
# @author Disparity <disparity-github@yandex.ru>
# @site https://github.com/Disparity/git-hooks

for i in $(git diff --cached --name-only|grep .php); do
    php -l ${i} | grep 'No syntax errors detected in' > /dev/null || exit -1
done
