#!/bin/bash
#
# PHP coding standards fixer
#
# @author Disparity <disparity-github@yandex.ru>
# @site https://github.com/Disparity/git-hooks
# @dependency git
# @dependency php@>=5.4
# @dependency php-cs-fixer@>=1.10.1

php_cs_fixer="`git rev-parse --show-toplevel`/vendor/bin/php-cs-fixer --config-file=`git rev-parse --show-toplevel`/.php_cs fix --quiet --no-interaction"

for i in $(git diff --diff-filter=AM --cached --name-only|grep .php); do
    $php_cs_fixer ${i} || git add -- ${i}
done
exit 0
